ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include




urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('ProyectoWebApp.urls')),

    path('servicios/', include('servicios.urls')),

    path('blog/', include('blog.urls')),

    path('contacto/', include('contacto.urls')),

    path('tienda/', include('tienda.urls')),

    path('carro/', include('carro.urls')),

    path('autenticacion/', include('autenticacion.urls')),
    
    path('pedidos/', include('pedidos.urls')),
    

]

blog/urls.py
from django.urls import path

from  blog.views import *

urlpatterns = [
    
    path('', blog, name="Blog"),
    path("categoria/<int:categoria_id>/", categoria, name="categoria" )
    


]

carro/urls.py
from django.urls import path

from  . import views

app_name= "carro"

urlpatterns = [
   
    path('agregar/<int:producto_id>', views.agregar_producto, name="agregar"),

    path('eliminar/<int:producto_id>', views.eliminar_producto, name="eliminar"),

    path('restar/<int:producto_id>', views.restar_producto, name="restar"),

    path('limpiar/', views.limpiar_carroproducto, name="limpiar"),


    
    


]

tienda/urls.py
from django.urls import path

from  tienda.views import *


urlpatterns = [
   
    path('', tienda, name="Tienda"),
    
    

]

carro/models.py
from django.db import models

# Create your models here.

tienda/models.py
from django.db import models
from django.contrib.auth.models import User


class CategoriaProd(models.Model):
    nombre= models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated= models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name= "categoriaprod"
        verbose_name_plural="categoriasprod"

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    nombre= models.CharField(max_length=50) 
    categorias= models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="tienda", null= True, blank=True)
    precio= models.FloatField()
    cantidad= models.BooleanField()

    created = models.DateTimeField(auto_now_add=True)
    updated= models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name= "Producto"
        verbose_name_plural="Productos"

    def __str__(self):
        return self.nombre 

carro/views.py
from django.shortcuts import render,redirect

from .carro import Carro
from tienda.models import Producto


# Create your views here.

def agregar_producto(request,producto_id):
    carro= Carro(request)
    producto= Producto.objects.get(id=producto_id)

    carro.agregar(producto=producto)
    
    return redirect("Tienda")



def eliminar_producto(request,producto_id):
    carro= Carro(request)
    producto= Producto.objects.get(id=producto_id)

    carro.eliminar_carrito(producto=producto)
    
    return redirect("Tienda")





def restar_producto(request,producto_id):
    carro= Carro(request)
    producto= Producto.objects.get(id=producto_id)

    carro.restar_producto(producto=producto)
    
    return redirect("Tienda")


def limpiar_carroproducto(request):
    carro= Carro(request)
    carro.limpiar_carrito()
    
    return redirect("Tienda")

tienda/views.py
from django.shortcuts import render
from .models import Producto
from . import views



def tienda(request):

    productos= Producto.objects.all()

    return render(request,"tienda/tienda.html", {"productos":productos})

tienda/templates/carro/widget.html
<table class="table table-bordered" style="
color: rgba(255, 255, 255, 0.7); 
background-color: rgba(18, 82, 140 , 0.8);
font-family:'Helvetica';
margin-left: 10px;">

        <thead>

            <tr>

                <th colspan="3" class="text-center">
                    Carrito Compras

                </th>
                

            </tr>

            <tr>
                <th>Producto</th>
                <th>Cantidad</th>
                <th>Suma</th>
            </tr>

        </thead>

        <tbody style="background-color: rgba(56, 106, 157, 0.8);">
            {% if request.session.carro.items %}

                {% for key, value in request.session.carro.items %}
                    <tr class="text-center">

                        <td>{{value.nombre}}</td>
                        <td>{{value.cantidad}}</td>
                        <td>
                            
                            <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success" style="
                                background-color: rgba(18, 82, 140 , 0.8);
                                border-color: #1E5B99 ;">+</a>

                            <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success" style="
                                background-color: rgba(18, 82, 140 , 0.8);
                                border-color: #1E5B99 ;">-</a><br>
                            {{value.precio}} CLP
                        </td>

                    </tr>

                {% endfor %}

            {% else %}
                <tr>
                    <td colspan="3">
                        <div class="alert alert-danger text-center" 
                        style="
                        color: rgba(255, 255, 255, 0.7); 
                        background-color: rgba(18, 82, 140 , 0.8);
                        font-family:'Helvetica';
                        ">
                            ¡No agregaste productos!
                        </div>

                    </td>
                </tr>
                
            {% endif %}

        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" style="
                color: rgba(255, 255, 255, 0.7); 
                background-color: rgb(255, 255, 255);
                font-family:'Helvetica';
                ">
                    
                    <a href="#" onclick="mostrarMensaje()">Pagar Total: {{ importe_total_carro }} CLP</a>

                    <script>
                    function mostrarMensaje() {
                        alert('¡Gracias por tu compra!');
                    }
                    </script>
                </td>
            </tr>
        </tfoot>
        
            
</table>